targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: tetsu_app|lib/apis/anichart/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: tetsu_app|lib/apis/anichart/schema.graphql
