// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:gql_code_builder_serializers/gql_code_builder_serializers.dart'
    show OperationSerializer;
import 'package:tetsu_app/apis/anichart/__generated__/schema.schema.gql.dart'
    show
        GActivitySort,
        GActivityType,
        GAiringScheduleInput,
        GAiringSort,
        GAniChartHighlightInput,
        GCharacterNameInput,
        GCharacterRole,
        GCharacterSort,
        GCountryCode,
        GExternalLinkMediaType,
        GExternalLinkType,
        GFuzzyDateInput,
        GFuzzyDateInt,
        GJson,
        GLikeableType,
        GListActivityOptionInput,
        GMediaExternalLinkInput,
        GMediaFormat,
        GMediaListOptionsInput,
        GMediaListSort,
        GMediaListStatus,
        GMediaRankType,
        GMediaRelation,
        GMediaSeason,
        GMediaSort,
        GMediaSource,
        GMediaStatus,
        GMediaTitleInput,
        GMediaTrendSort,
        GMediaType,
        GModActionType,
        GModRole,
        GNotificationOptionInput,
        GNotificationType,
        GRecommendationRating,
        GRecommendationSort,
        GReviewRating,
        GReviewSort,
        GRevisionHistoryAction,
        GScoreFormat,
        GSiteTrendSort,
        GStaffLanguage,
        GStaffNameInput,
        GStaffSort,
        GStudioSort,
        GSubmissionSort,
        GSubmissionStatus,
        GThreadCommentSort,
        GThreadSort,
        GUserSort,
        GUserStaffNameLanguage,
        GUserStatisticsSort,
        GUserTitleLanguage;
import 'package:tetsu_app/apis/anichart/queries/__generated__/airing.data.gql.dart'
    show
        GAlAiringData,
        GAlAiringData_Page,
        GAlAiringData_Page_media,
        GAlAiringData_Page_media_coverImage,
        GAlAiringData_Page_media_externalLinks,
        GAlAiringData_Page_media_nextAiringEpisode,
        GAlAiringData_Page_media_studios,
        GAlAiringData_Page_media_studios_nodes,
        GAlAiringData_Page_media_title,
        GAlAiringData_Page_pageInfo;
import 'package:tetsu_app/apis/anichart/queries/__generated__/airing.req.gql.dart'
    show GAlAiringReq;
import 'package:tetsu_app/apis/anichart/queries/__generated__/airing.var.gql.dart'
    show GAlAiringVars;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GActivitySort,
  GActivityType,
  GAiringScheduleInput,
  GAiringSort,
  GAlAiringData,
  GAlAiringData_Page,
  GAlAiringData_Page_media,
  GAlAiringData_Page_media_coverImage,
  GAlAiringData_Page_media_externalLinks,
  GAlAiringData_Page_media_nextAiringEpisode,
  GAlAiringData_Page_media_studios,
  GAlAiringData_Page_media_studios_nodes,
  GAlAiringData_Page_media_title,
  GAlAiringData_Page_pageInfo,
  GAlAiringReq,
  GAlAiringVars,
  GAniChartHighlightInput,
  GCharacterNameInput,
  GCharacterRole,
  GCharacterSort,
  GCountryCode,
  GExternalLinkMediaType,
  GExternalLinkType,
  GFuzzyDateInput,
  GFuzzyDateInt,
  GJson,
  GLikeableType,
  GListActivityOptionInput,
  GMediaExternalLinkInput,
  GMediaFormat,
  GMediaListOptionsInput,
  GMediaListSort,
  GMediaListStatus,
  GMediaRankType,
  GMediaRelation,
  GMediaSeason,
  GMediaSort,
  GMediaSource,
  GMediaStatus,
  GMediaTitleInput,
  GMediaTrendSort,
  GMediaType,
  GModActionType,
  GModRole,
  GNotificationOptionInput,
  GNotificationType,
  GRecommendationRating,
  GRecommendationSort,
  GReviewRating,
  GReviewSort,
  GRevisionHistoryAction,
  GScoreFormat,
  GSiteTrendSort,
  GStaffLanguage,
  GStaffNameInput,
  GStaffSort,
  GStudioSort,
  GSubmissionSort,
  GSubmissionStatus,
  GThreadCommentSort,
  GThreadSort,
  GUserSort,
  GUserStaffNameLanguage,
  GUserStatisticsSort,
  GUserTitleLanguage,
])
final Serializers serializers = _serializersBuilder.build();
